name: Testes Automatizados

on:
  push:
    branches:
      - master

jobs:
  testes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do projeto
        uses: actions/checkout@v3

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Dar permissão ao Maven Wrapper
        run: chmod +x mvnw

      - name: Executar testes
        run: ./mvnw test